import { html } from "lit";
import "../../frontend/components/features/ollama-project-view.js";

const tree = {
  name: "my-project",
  type: "directory",
  children: [
    { name: "index.html", type: "file", path: "index.html" },
    { name: "styles", type: "directory", children: [
      { name: "main.css", type: "file", path: "styles/main.css" }
    ] },
    { name: "src", type: "directory", children: [
      { name: "app.js", type: "file", path: "src/app.js" },
      { name: "data.json", type: "file", path: "src/data.json" }
    ] }
  ]
};

export default {
  title: "Feature/Ollama Project View",
  component: "ollama-project-view",
  args: {
    projectName: "Demo Project",
    description: "Generated by Ollama Chat",
    fileCount: "4",
    selectedPath: "src/app.js",
    fileLanguage: "js",
    fileSize: "1.2 KB",
    fileLines: "24",
    fileContent: "const greeting = 'Hello';\nconsole.log(greeting);\n",
  },
  argTypes: {
    projectName: { control: "text" },
    description: { control: "text" },
    fileCount: { control: "text" },
    selectedPath: { control: "text" },
    fileLanguage: { control: "text" },
    fileSize: { control: "text" },
    fileLines: { control: "text" },
    fileContent: { control: "text" },
  },
};

const Template = ({
  projectName,
  description,
  fileCount,
  selectedPath,
  fileLanguage,
  fileSize,
  fileLines,
  fileContent,
}) => html`
  <div style="height: 420px;">
    <ollama-project-view
      project-name=${projectName}
      description=${description}
      file-count=${fileCount}
      selected-path=${selectedPath}
      file-language=${fileLanguage}
      file-size=${fileSize}
      file-lines=${fileLines}
      file-content=${fileContent}
      tree='${JSON.stringify(tree)}'
    ></ollama-project-view>
  </div>
`;

export const Default = Template.bind({});
