import { html } from "lit";
import "../../frontend/components/features/ollama-chat-container.js";
import "../../frontend/components/features/ollama-conversation-list.js";
import "../../frontend/components/features/ollama-conversation-item.js";
import "../../frontend/components/features/ollama-chat-input.js";
import "../../frontend/components/features/ollama-message-list.js";
import "../../frontend/components/features/ollama-user-message.js";
import "../../frontend/components/features/ollama-ai-response.js";
import "../../frontend/components/features/ollama-live-preview.js";
import "../../frontend/components/features/ollama-project-view.js";
import "../../frontend/components/features/ollama-sidebar-user.js";
import "../../frontend/components/base/ollama-button.js";
import "../../frontend/components/base/ollama-icon.js";
import "../../frontend/components/base/ollama-text.js";
import "../../frontend/components/base/ollama-tooltip.js";
import "../../frontend/components/base/ollama-toggle-switch.js";

class AppShellPreviewDemo extends HTMLElement {
  constructor() {
    super();
    this.mode = "chat";
    this.sidebarOpen = true;
    this.projectExpanded =
      '["my-project","my-project/src","my-project/styles"]';
    this.projectSelected = "src/app.js";
  }

  connectedCallback() {
    this.render();
  }

  setMode(next) {
    this.mode = next;
    this.render();
  }

  attachListeners() {
    const toggle = this.querySelector("ollama-toggle-switch");
    if (toggle) {
      toggle.addEventListener("change", (event) => {
        const value = event.detail?.value;
        this.setMode(value === "right" ? "project" : "chat");
      });
    }

    const container = this.querySelector("ollama-chat-container");
    if (container) {
      container.addEventListener("sidebar-toggle", (event) => {
        const open = event.detail?.open;
        this.sidebarOpen = Boolean(open);
      });
    }

    const projectView = this.querySelector("ollama-project-view");
    if (projectView) {
      projectView.addEventListener("file-selected", (event) => {
        this.projectSelected = event.detail?.path || this.projectSelected;
      });
      projectView.addEventListener("expanded-change", (event) => {
        const expanded = event.detail?.expanded || [];
        this.projectExpanded = JSON.stringify(expanded);
      });
    }
  }

  render() {
    const showProject = this.mode === "project";
    this.innerHTML = `
      <ollama-chat-container ${
        !showProject && this.sidebarOpen ? "sidebar-open" : ""
      }>
        <nav
          slot="sidebar"
          aria-label="Conversations"
          style="display: flex; flex-direction: column; gap: 16px; height: 100%;"
        >
          <div style="padding: 16px; display: flex; flex-direction: column; gap: 16px;">
            <ollama-text variant="title" size="md" weight="semibold">
              Sidebar
            </ollama-text>
            <div style="margin: 12px 0;">
              <ollama-button variant="secondary">New Chat</ollama-button>
            </div>
            <ollama-conversation-list>
              <ollama-conversation-item
                conversation-id="conv-1"
                conversation-title="Project kickoff"
                preview="Outline milestones and action items"
                model="llama3"
                timestamp="2h ago"
                unread-count="2"
                selected
              ></ollama-conversation-item>
              <ollama-conversation-item
                conversation-id="conv-2"
                conversation-title="Design review"
                preview="Summarize visual polish requests"
                model="mistral"
                timestamp="Yesterday"
              ></ollama-conversation-item>
            </ollama-conversation-list>
          </div>
          <div style="margin-top: auto;">
            <ollama-sidebar-user
              name="Kevin Hill"
              logged-in
            ></ollama-sidebar-user>
          </div>
        </nav>
        <header slot="header" aria-label="App bar"></header>
        <div slot="header-controls" aria-label="Header controls">
          <ollama-toggle-switch
            value="${showProject ? "right" : "left"}"
            left-label="Chat"
            right-label="Project"
          ></ollama-toggle-switch>
        </div>
        <main slot="main" aria-label="Chat messages" style="height: 100%;">
          ${
            showProject
              ? `
              <div style="position: relative; height: 100%;">
                <ollama-project-view
                  project-name="Demo Project"
                  description="Generated by Ollama Chat"
                  file-count="4"
                  selected-path="${this.projectSelected}"
                  file-language="js"
                  file-size="1.2 KB"
                  file-lines="24"
                  file-content="const greeting = 'Hello';\nconsole.log(greeting);\n"
                  expanded='${this.projectExpanded}'
                  tree='{"name":"my-project","type":"directory","children":[{"name":"index.html","type":"file","path":"index.html"},{"name":"styles","type":"directory","children":[{"name":"main.css","type":"file","path":"styles/main.css"}]},{"name":"src","type":"directory","children":[{"name":"app.js","type":"file","path":"src/app.js"},{"name":"data.json","type":"file","path":"src/data.json"}]}]}'
                ></ollama-project-view>
                <div style="margin-top: 12px; height: 240px;">
                  <ollama-live-preview
                    title="Preview"
                    srcdoc='<!doctype html><html><body style="font-family: system-ui; padding: 24px;"><h2>Live preview</h2><p>Project preview area.</p></body></html>'
                  ></ollama-live-preview>
                </div>
              </div>
              `
              : `
              <ollama-message-list auto-scroll>
                <ollama-user-message
                  content="Can you draft the first milestone summary? Make it short and clear."
                  timestamp="2m ago"
                  model="llama3"
                  tokens="128"
                ></ollama-user-message>
                <ollama-ai-response
                  content="Sure. Milestone 1 focuses on stable chat UI, core component coverage, and accessibility cleanup."
                  timestamp="Just now"
                  model="llama3"
                  tokens="512"
                  streaming
                ></ollama-ai-response>
              </ollama-message-list>
              `
          }
        </main>
        ${
          showProject
            ? ""
            : `
          <footer
            slot="footer"
            aria-label="Chat composer"
            style="padding: 12px 16px;"
          >
            <ollama-chat-input></ollama-chat-input>
          </footer>
        `
        }
      </ollama-chat-container>
    `;
    this.attachListeners();
  }
}

if (!customElements.get("ollama-app-shell-demo")) {
  customElements.define("ollama-app-shell-demo", AppShellPreviewDemo);
}

export default {
  title: "Feature/Application Layout",
  parameters: {
    layout: "fullscreen",
  },
};

export const AppShell = () =>
  html`<ollama-app-shell-demo></ollama-app-shell-demo>`;
